from __future__ import annotations

import json
from copy import deepcopy
from typing import Any

from .base import BaseProvider, ProviderResponse


class GeminiProvider(BaseProvider):
    """Google Gemini GenerateContent adapter with function-tool support."""

    def supports_function_tools(self) -> bool:
        return True

    @staticmethod
    def _clean_schema(value: Any) -> Any:
        """Convert an OpenAI-style JSON Schema to Gemini's supported subset."""
        if isinstance(value, list):
            return [GeminiProvider._clean_schema(item) for item in value]
        if not isinstance(value, dict):
            return value

        unsupported = {
            "$schema",
            "$id",
            "$ref",
            "$defs",
            "definitions",
            "additionalProperties",
            "patternProperties",
            "unevaluatedProperties",
            "examples",
            "example",
            "default",
            "const",
            "readOnly",
            "writeOnly",
            "deprecated",
        }
        cleaned = {}
        for key, item in value.items():
            if key in unsupported:
                continue
            cleaned[key] = GeminiProvider._clean_schema(item)

        # Gemini function declarations require an object root schema.
        if cleaned.get("type") == "object":
            cleaned.setdefault("properties", {})
        return cleaned

    @classmethod
    def _convert_tools(cls, tools):
        declarations = []
        for tool in tools or []:
            fn = (tool or {}).get("function") or {}
            name = (fn.get("name") or "").strip()
            if not name:
                continue
            declarations.append(
                {
                    "name": name,
                    "description": fn.get("description") or "",
                    "parameters": cls._clean_schema(
                        fn.get("parameters")
                        or {"type": "object", "properties": {}}
                    ),
                }
            )
        return [{"functionDeclarations": declarations}] if declarations else []

    @staticmethod
    def _json_value(value):
        if not isinstance(value, str):
            return value
        try:
            return json.loads(value)
        except Exception:
            return value

    @classmethod
    def _assistant_parts(cls, message):
        parts = []
        content = message.get("content")
        if content:
            parts.append({"text": str(content)})

        for call in message.get("tool_calls") or []:
            # Calls generated by this adapter retain the original Gemini part so
            # thought signatures and provider metadata survive the next turn.
            original = call.get("_gemini_part") if isinstance(call, dict) else None
            if isinstance(original, dict) and original.get("functionCall"):
                parts.append(deepcopy(original))
                continue

            fn = (call or {}).get("function") or {}
            args = cls._json_value(fn.get("arguments") or {})
            function_call = {
                "name": fn.get("name") or (call or {}).get("name"),
                "args": args if isinstance(args, dict) else {"value": args},
            }
            if (call or {}).get("id"):
                function_call["id"] = call.get("id")
            parts.append({"functionCall": function_call})
        return parts or [{"text": ""}]

    @classmethod
    def _messages_to_contents(cls, messages):
        contents = []
        for message in messages or []:
            role = message.get("role")

            if role == "assistant":
                contents.append(
                    {"role": "model", "parts": cls._assistant_parts(message)}
                )
                continue

            if role == "tool":
                result = cls._json_value(message.get("content") or "")
                response = result if isinstance(result, dict) else {"result": result}
                function_response = {
                    "name": message.get("name") or "tool",
                    "response": {"result": response},
                }
                if message.get("tool_call_id"):
                    function_response["id"] = message.get("tool_call_id")
                contents.append(
                    {
                        "role": "user",
                        "parts": [{"functionResponse": function_response}],
                    }
                )
                continue

            # System prompts are sent separately through systemInstruction.
            if role == "system":
                continue
            contents.append(
                {
                    "role": "user",
                    "parts": [{"text": str(message.get("content") or "")}],
                }
            )
        return contents

    @staticmethod
    def _extract_parts(data):
        candidates = data.get("candidates") or []
        if not candidates:
            return []
        return ((candidates[0] or {}).get("content") or {}).get("parts") or []

    @classmethod
    def _extract_text_and_calls(cls, data):
        text_chunks = []
        calls = []
        for index, part in enumerate(cls._extract_parts(data)):
            if not isinstance(part, dict):
                continue
            if part.get("text"):
                text_chunks.append(str(part.get("text")))

            function_call = part.get("functionCall") or part.get("function_call")
            if not isinstance(function_call, dict):
                continue

            call_id = function_call.get("id") or f"gemini-call-{index + 1}"
            name = function_call.get("name")
            args = function_call.get("args") or {}
            raw_call = {
                "id": call_id,
                "type": "function",
                "function": {
                    "name": name,
                    "arguments": json.dumps(args, ensure_ascii=False),
                },
                "_gemini_part": deepcopy(part),
            }
            calls.append(
                {
                    "id": call_id,
                    "name": name,
                    "arguments": args if isinstance(args, dict) else {"value": args},
                    "raw": raw_call,
                }
            )
        return "".join(text_chunks).strip(), calls

    @staticmethod
    def _compat_raw(data, text, calls):
        """Add an OpenAI-like message view used by the shared tool loop."""
        raw = deepcopy(data)
        finish_reason = None
        candidates = data.get("candidates") or []
        if candidates:
            finish_reason = (candidates[0] or {}).get("finishReason")
        raw["choices"] = [
            {
                "message": {
                    "role": "assistant",
                    "content": text or "",
                    "tool_calls": [call.get("raw") for call in calls],
                },
                "finish_reason": finish_reason,
            }
        ]
        raw["_gemini_response"] = deepcopy(data)
        return raw

    def chat(self, messages, system_prompt="", tools=None):
        base = (
            self.config.base_url
            or "https://generativelanguage.googleapis.com/v1beta"
        ).rstrip("/")
        key = self.config.get_password("api_key", raise_exception=False) or ""
        if not key:
            raise RuntimeError("Gemini API Key is not configured.")

        model = (self.config.default_model or "").strip()
        if model.startswith("models/"):
            model = model.removeprefix("models/")
        if not model:
            raise RuntimeError("Gemini model is not configured.")

        payload = {
            "contents": self._messages_to_contents(messages),
            "generationConfig": {
                "temperature": float(self.config.temperature or 0.2),
                "maxOutputTokens": int(self.config.max_output_tokens or 2048),
            },
        }
        if system_prompt:
            payload["systemInstruction"] = {"parts": [{"text": system_prompt}]}

        gemini_tools = self._convert_tools(tools)
        if gemini_tools:
            payload["tools"] = gemini_tools
            payload["toolConfig"] = {
                "functionCallingConfig": {"mode": "AUTO"}
            }

        data = self.post(
            f"{base}/models/{model}:generateContent",
            headers={
                "x-goog-api-key": key,
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            json=payload,
        )
        text, calls = self._extract_text_and_calls(data)
        if not text and not calls:
            raise RuntimeError(self.empty_response_reason(data))

        raw = self._compat_raw(data, text, calls)
        return ProviderResponse(
            text=text,
            raw=raw,
            usage=data.get("usageMetadata"),
            tool_calls=calls,
        )
